trigger: none

parameters:
- name: action
  displayName: Terraform Action
  type: string
  default: plan
  values:
  - plan
  - apply
  - destroy

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureTerraform'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      wget https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip

      sudo apt-get update
      sudo apt-get install unzip -y

      unzip terraform_1.8.5_linux_amd64.zip
      sudo mv terraform /usr/local/bin/

      terraform version

      cd terraform

      terraform init
      terraform validate

      terraform ${{ parameters.action }} -auto-approve