trigger: none

parameters:
- name: terraformAction
  displayName: Terraform Action
  type: string
  default: plan
  values:
    - plan
    - apply
    - destroy

pool:
  vmImage: 'ubuntu-latest'

steps:

# Install Terraform
- script: |
    sudo apt-get update
    sudo apt-get install -y wget unzip

    wget -q https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip

    unzip -o terraform_1.8.5_linux_amd64.zip

    sudo chmod +x terraform
    sudo mv terraform /usr/local/bin/

    terraform version
  displayName: 'Install Terraform'

# Terraform Init
- script: |
    terraform init
  workingDirectory: $(Build.SourcesDirectory)/infra
  displayName: 'Terraform Init'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

# Terraform Validate
- script: |
    terraform validate
  workingDirectory: $(Build.SourcesDirectory)/infra
  displayName: 'Terraform Validate'

# Terraform Plan
- script: |
    terraform plan -out=tfplan
  workingDirectory: $(Build.SourcesDirectory)/infra
  displayName: 'Terraform Plan'
  condition: eq('${{ parameters.terraformAction }}','plan')
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

# Terraform Apply
- script: |
    terraform apply -auto-approve
  workingDirectory: $(Build.SourcesDirectory)/infra
  displayName: 'Terraform Apply'
  condition: eq('${{ parameters.terraformAction }}','apply')
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

# Terraform Destroy
- script: |
    terraform destroy -auto-approve
  workingDirectory: $(Build.SourcesDirectory)/infra
  displayName: 'Terraform Destroy'
  condition: eq('${{ parameters.terraformAction }}','destroy')
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
