trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: TerraformPlan
  displayName: "Terraform Plan"

  jobs:
  - job: Plan
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureTerraform'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform

          terraform init

          terraform validate

          terraform plan -out=tfplan

- stage: TerraformApply
  displayName: "Terraform Apply"
  dependsOn: TerraformPlan

  jobs:
  - deployment: Apply
    environment: terraform-approval

    strategy:
      runOnce:
        deploy:
          steps:

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureTerraform'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                cd terraform

                terraform init

                terraform apply -auto-approve